      common/probparams/APPROX_RIEM_SOLVE,EXACT_RIEM_SOLVE,
     &  HLLC_RIEM_SOLVE,
     &  PIECEWISE_CONSTANT_X,PIECEWISE_CONSTANT_Y,PIECEWISE_CONSTANT_Z,
     &  SPHERE,STEP,
     &  CELLG,FACEG,FLUXG
      integer 
     &  APPROX_RIEM_SOLVE,EXACT_RIEM_SOLVE,HLLC_RIEM_SOLVE,
     &  PIECEWISE_CONSTANT_X,PIECEWISE_CONSTANT_Y,PIECEWISE_CONSTANT_Z,
     &  SPHERE,STEP,
     &  CELLG,FACEG,FLUXG

