#!/bin/sh

dir=$1

cd $dir
files=$(ls *.html)
echo $files
for i in $files ; do
  echo $i
#  sed 's#99%#100%#' $i > tmp ;
  sed '/line_tl.gif/{s#line_tl.gif" height="7" width="116" border="0">#line_tl.gif" height="7" width="116" border="0"></td>#;n;d}' $i > tmp;
  mv tmp $i ;
  sed 's#head_bottom_right.png" height="120" width="720" border="0">#head_bottom_right.png" height="120" width="720" border="0"><br>#' $i > tmp;
  mv tmp $i ;
  sed '/line_tr.gif/{s#line_tr.gif" height="7" width="720" border="0">#line_tr.gif" height="7" width="720" border="0"></td>#;n;d}' $i > tmp;
  mv tmp $i ;
done

