#!/bin/bash
#########################################################################
##
## This file is part of the SAMRAI distribution.  For full copyright 
## information, see COPYRIGHT and COPYING.LESSER. 
##
## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
## Description:   Commands to create the autoconf configure script
##
#########################################################################

rm -fr autom4te.cache
rm -fr config/aclocal.m4
aclocal -I `pwd`/config --output=config/aclocal.m4
autoheader -I config
sed -i -e 's/^\(#undef \(PACKAGE\|VERSION\)\)/\/\/ Removed due to name conflict \1/' config/SAMRAI_config.h.in
autoconf -I config
