#!/bin/sh
#########################################################################
##
## This file is part of the SAMRAI distribution.  For full copyright 
## information, see COPYRIGHT and COPYING.LESSER. 
##
## Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
## Description:   shell script to run updateXd, include, and depend
##
#########################################################################

BIN=`dirname $0`

perl $BIN/updateXd.pl
sh $BIN/depend

if test -n "`pwd | grep ./source/.`" ; then
   echo "Warning - you may need to re-run $BIN/depend in SAMRAI/source..."
fi

exit 0
