/*************************************************************************
 *
 * This file is part of the SAMRAI distribution.  For full copyright
 * information, see COPYRIGHT and COPYING.LESSER.
 *
 * Copyright:     (c) 1997-2012 Lawrence Livermore National Security, LLC
 * Description:   Test program for performance and quality of TreeLoadBalancer.
 *
 ************************************************************************/
#include "SAMRAI/SAMRAI_config.h"

#include <iomanip>

#include "SAMRAI/mesh/BergerRigoutsos.h"
#include "SAMRAI/hier/BoxLevel.h"
#include "SAMRAI/hier/BoxLevelStatistics.h"
#include "SAMRAI/hier/IntVector.h"
#include "SAMRAI/geom/CartesianGridGeometry.h"
#include "SAMRAI/geom/CartesianPatchGeometry.h"
#include "SAMRAI/pdat/CellData.h"
#include "SAMRAI/pdat/CellVariable.h"
#include "SAMRAI/pdat/NodeData.h"
#include "SAMRAI/hier/Connector.h"
#include "SAMRAI/hier/ConnectorStatistics.h"
#include "SAMRAI/hier/BoxLevelConnectorUtils.h"
#include "SAMRAI/hier/OverlapConnectorAlgorithm.h"
#include "SAMRAI/hier/MappingConnectorAlgorithm.h"
#include "SAMRAI/mesh/BalanceUtilities.h"
#include "SAMRAI/mesh/TreeLoadBalancer.h"
#include "SAMRAI/mesh/TreeLoadBalancerOld.h"
#include "SAMRAI/mesh/ChopAndPackLoadBalancer.h"
#include "SAMRAI/hier/VariableDatabase.h"
#include "SAMRAI/appu/VisItDataWriter.h"

#include "SAMRAI/tbox/InputDatabase.h"
#include "SAMRAI/tbox/InputManager.h"
#include "SAMRAI/tbox/MathUtilities.h"
#include "SAMRAI/tbox/SAMRAIManager.h"
#include "SAMRAI/tbox/TimerManager.h"
#include <vector>

#include "DerivedVisOwnerData.h"
#include "SinusoidalFrontGenerator.h"
#include "SphericalShellGenerator.h"

using namespace SAMRAI;
using namespace tbox;

/*
 ************************************************************************
 *
 *
 *************************************************************************
 */

void enforceNesting(
   hier::BoxLevel& L1,
   hier::Connector& L0_to_L1,
   hier::Connector& L1_to_L0,
   const boost::shared_ptr<hier::PatchHierarchy>& hierarchy,
   int coarser_ln);

void
sortNodes(
   hier::BoxLevel& new_box_level,
   hier::Connector& tag_to_new,
   hier::Connector& new_to_tag,
   bool sort_by_corners,
   bool sequentialize_global_indices);

void
refineHead(
   hier::BoxLevel& head,
   hier::Connector& ref_to_head,
   hier::Connector& head_to_ref,
   const hier::IntVector &refinement_ratio );

void outputPostcluster(
   const hier::BoxLevel &cluster,
   const hier::BoxLevel &ref,
   const hier::IntVector &ref_to_cluster_width,
   const std::string &border );

void outputPrebalance(
   const hier::BoxLevel &pre,
   const hier::BoxLevel &ref,
   const hier::IntVector &pre_width,
   const std::string &border );

void outputPostbalance(
   const hier::BoxLevel &post,
   const hier::BoxLevel &ref,
   const hier::IntVector &post_width,
   const std::string &border );

boost::shared_ptr<mesh::LoadBalanceStrategy>
createLoadBalancer(
   boost::shared_ptr<tbox::Database> &input_db,
   const std::string &lb_type,
   int ln,
   const tbox::Dimension &dim );


/*
********************************************************************************
*
* Performance testing for load balancers.
*
* 1. Build "level 0" from the domain description (input parameter
* "domain_boxes").  L0 is for doing the test, not for checking load
* balancer performance.
*
* 2. Build "level 1" and write out performance data for balancing it.
*
* 3. Build "level 2" and write out performance data for balancing it.
* The prebalance boxes for L2 are generated by clustering tags on L1.
* All L1 cells are tagged except for a small margin by the L1 boundary
* (input parameter "tag_margin".  This configuration tries to mimick
* real problems where the tags occupy a large portion of the tag
* level, leading to a greater number of owners for prebalance boxes.
*
********************************************************************************
*/

int main(
   int argc,
   char* argv[])
{
   /*
    * Initialize MPI, SAMRAI.
    */

   SAMRAI_MPI::init(&argc, &argv);
   SAMRAIManager::initialize();
   SAMRAIManager::startup();
   tbox::SAMRAI_MPI mpi(tbox::SAMRAI_MPI::getSAMRAIWorld());

   const int rank = mpi.getRank();
   int fail_count = 0;

   /*
    * Process command line arguments.  For each run, the input
    * filename must be specified.  Usage is:
    *
    * executable <input file name>
    */
   std::string input_filename;

   if (argc < 2) {
      TBOX_ERROR("USAGE:  " << argv[0] << " <input file> [case name]\n"
                            << "  options:\n"
                            << "  none at this time" << std::endl);
   } else {
      input_filename = argv[1];
   }

   std::string case_name;
   if (argc > 2) {
      case_name = argv[2];
   }

   {
      /*
       * Scope to force destruction of objects that would otherwise
       * leave allocated memory reported by the memory test.
       */

      /*
       * Create input database and parse all data in input file.
       */

      boost::shared_ptr<InputDatabase> input_db(new InputDatabase("input_db"));
      boost::shared_ptr<Database> base_db(input_db);
      tbox::InputManager::getManager()->parseInputFile(input_filename, input_db);

      /*
       * Set up the timer manager.
       */
      if (input_db->isDatabase("TimerManager")) {
         TimerManager::createManager(input_db->getDatabase("TimerManager"));
      }

      /*
       * Retrieve "Main" section from input database.
       * The main database is used only in main().
       * The base_name variable is a base name for
       * all name strings in this program.
       */

      boost::shared_ptr<Database> main_db = input_db->getDatabase("Main");

      const tbox::Dimension
         dim(static_cast<unsigned short>(main_db->getInteger("dim")));

      const hier::IntVector &zero_vec = hier::IntVector::getZero(dim);

      std::string base_name = "unnamed";
      base_name = main_db->getStringWithDefault("base_name", base_name);

      /*
       * Modify basename for this particular run.
       * Add the number of processes and the case name.
       */
      if (!case_name.empty()) {
         base_name = base_name + '-' + case_name;
      }
      base_name = base_name + '-' + tbox::Utilities::intToString(
            mpi.getSize(),
            5);
      tbox::plog << "Added case name (" << case_name << ") and nprocs ("
                 << mpi.getSize() << ") to base name -> '"
                 << base_name << "'\n";

      if (!case_name.empty()) {
         tbox::plog << "Added case name (" << case_name << ") and nprocs ("
                    << mpi.getSize() << ") to base name -> '"
                    << base_name << "'\n";
      }

      /*
       * Start logging.
       */
      const std::string log_file_name = base_name + ".log";
      bool log_all_nodes = false;
      log_all_nodes = main_db->getBoolWithDefault("log_all_nodes",
            log_all_nodes);
      if (log_all_nodes) {
         PIO::logAllNodes(log_file_name);
      } else {
         PIO::logOnlyNodeZero(log_file_name);
      }


      /*
       * Whether to perform certain steps in mesh generation.
       */

      tbox::Array<bool> enforce_nesting(1, true);
      if ( main_db->isBool("enforce_nesting") ) {
         enforce_nesting = main_db->getBoolArray("enforce_nesting");
      }

      tbox::Array<bool> load_balance(1, true);
      if ( main_db->isBool("load_balance") ) {
         load_balance = main_db->getBoolArray("load_balance");
      }



      /*
       * Parameters.  Some of these can be specified by input deck.
       */
      hier::IntVector ghost_cell_width(dim, 2);
      if (main_db->isInteger("ghost_cell_width")) {
         main_db->getIntegerArray("ghost_cell_width", &ghost_cell_width[0], dim.getValue());
      }

      hier::IntVector bad_interval(dim, 2);
      hier::IntVector cut_factor(dim, 1);

      hier::OverlapConnectorAlgorithm oca;



      /*
       * Set up the domain from input.
       */

      hier::BoxContainer input_boxes(main_db->getDatabaseBoxArray("domain_boxes"));
      input_boxes.begin();

      hier::BoxContainer domain_boxes;
      hier::LocalId local_id(0);
      for (hier::BoxContainer::iterator itr = input_boxes.begin();
           itr != input_boxes.end(); ++itr) {
         itr->setBlockId(hier::BlockId(0));
         domain_boxes.pushBack(hier::Box(*itr, local_id++, 0));
      }

      std::vector<double> xlo(dim.getValue());
      std::vector<double> xhi(dim.getValue());
      for (int i = 0; i < dim.getValue(); ++i) {
         xlo[i] = 0.0;
         xhi[i] = 1.0;
      }
      if (main_db->isDouble("xlo")) {
         main_db->getDoubleArray("xlo", &xlo[0], dim.getValue());
      }
      if (main_db->isDouble("xhi")) {
         main_db->getDoubleArray("xhi", &xhi[0], dim.getValue());
      }


      /*
       * Choose the tagging code.
       */
      const std::string mesh_generator_name =
         main_db->getStringWithDefault("mesh_generator_name", "SinusoidalFrontGenerator");
      boost::shared_ptr<MeshGenerationStrategy> mesh_gen;
      if (mesh_generator_name == "SinusoidalFrontGenerator") {
         mesh_gen.reset(
            new SinusoidalFrontGenerator(
               "SinusoidalFrontGenerator",
               dim,
               main_db->getDatabaseWithDefault("SinusoidalFrontGenerator",
                                               boost::shared_ptr<tbox::Database>())));
      }
      else if (mesh_generator_name == "SphericalShellGenerator") {
         mesh_gen.reset(
            new SphericalShellGenerator(
               "SphericalShellGenerator",
               dim,
               main_db->getDatabaseWithDefault("SphericalShellGenerator",
                                               boost::shared_ptr<tbox::Database>())));
      }
      else {
         TBOX_ERROR("Unrecognized MeshGeneratorStrategy " << mesh_generator_name);
      }

      /*
       * If autoscale_base_nprocs is given, take the domain_boxes, xlo and xhi
       * to be the size for the (integer) value of autoscale_base_nprocs.  Scale
       * the problem from there to the number of process running by
       * doubling the dimension starting with the j direction.
       *
       * The number of processes must be a power of 2 times the value
       * of autoscale_base_nprocs.
       */
      const int autoscale_base_nprocs =
         main_db->getIntegerWithDefault("autoscale_base_nprocs", mpi.getSize());

      mesh_gen->setDomain( domain_boxes, &xlo[0], &xhi[0], autoscale_base_nprocs, mpi );


      hier::VariableDatabase* vdb = hier::VariableDatabase::getDatabase();

      {
         /*
          * Add a dummy PatchData with a big ghost width.
          * GridGeometry forbids increasing the max data ghost width
          * after it starts computing boundary boxes for a patch.  We
          * force it to accept a big ghost width here so that the
          * methods below (particularly those registering tag
          * data) won't crash by asking for more ghost width than what
          * was registered when the first boundary boxes were
          * computed.
          */

      boost::shared_ptr<pdat::CellVariable<int> > dummy_variable(
         new pdat::CellVariable<int>(dim, "DummyVariable"));

      boost::shared_ptr<hier::VariableContext> dummy_context =
         vdb->getContext("DUMMY");

      vdb->registerVariableAndContext(
         dummy_variable,
         dummy_context,
         hier::IntVector(dim,10));
      }


      /*
       * Clustering algorithm.
       */
      mesh::BergerRigoutsos abr(
         dim,
         main_db->getDatabaseWithDefault("BergerRigoutsos", boost::shared_ptr<tbox::Database>()) );
      double efficiency_tol = main_db->getDoubleWithDefault("efficiency_tol", 0.7);
      double combine_tol = main_db->getDoubleWithDefault("combine_tol", 0.7);

      /*
       * Create hierarchy.
       */

      boost::shared_ptr<geom::CartesianGridGeometry> grid_geometry(
         new geom::CartesianGridGeometry(
            "GridGeometry",
            &xlo[0],
            &xhi[0],
            domain_boxes));

      boost::shared_ptr<hier::PatchHierarchy> hierarchy(
         new hier::PatchHierarchy(
            "Hierarchy",
            grid_geometry,
            input_db->getDatabase("PatchHierarchy") ));

      mesh_gen->resetHierarchyConfiguration(hierarchy, 0, 1);

      enforce_nesting.resizeArray( hierarchy->getMaxNumberOfLevels(),
                                   bool(enforce_nesting.back()) );

      load_balance.resizeArray( hierarchy->getMaxNumberOfLevels(),
                                bool(load_balance.back()) );


      const int max_levels = hierarchy->getMaxNumberOfLevels();

      hier::BoxLevel domain_box_level(
         hier::IntVector(dim, 1),
         grid_geometry,
         tbox::SAMRAI_MPI::getSAMRAIWorld(),
         hier::BoxLevel::GLOBALIZED);
      for (hier::BoxContainer::const_iterator bi=grid_geometry->getPhysicalDomain().begin();
           bi!=grid_geometry->getPhysicalDomain().end(); ++bi) {
         domain_box_level.addBox(*bi);
      }


      /*
       * Set up the patch data for tags.
       */

      boost::shared_ptr<pdat::CellVariable<int> > tag_variable(
         new pdat::CellVariable<int>(dim, "ShrinkingLevelTagVariable"));

      boost::shared_ptr<hier::VariableContext> default_context =
         vdb->getContext("TagVariable");

      const int tag_data_id = vdb->registerVariableAndContext(
         tag_variable,
         default_context,
         hier::IntVector::getZero(dim));


      /*
       * Set up the load balancers.
       */

      std::string load_balancer_type =
         main_db->getStringWithDefault("load_balancer_type", "TreeLoadBalancer");


      plog << "Input database after initialization..." << std::endl;
      input_db->printClassData(plog);



      /*
       * Step 1: Build L0.
       */
      tbox::pout << "\n==================== Generating L0 ====================" << std::endl;


      {

         hier::BoxLevel L0(hier::IntVector(dim, 1), grid_geometry);

         hier::BoxContainer L0_boxes(
            grid_geometry->getPhysicalDomain() );
         const int boxes_per_proc =
            (L0_boxes.size() + L0.getMPI().getSize()
             - 1) / L0.getMPI().getSize();
         const int my_boxes_start = L0.getMPI().getRank()
            * boxes_per_proc;
         const int my_boxes_stop =
            tbox::MathUtilities<int>::Min(my_boxes_start + boxes_per_proc,
               L0_boxes.size());
         hier::BoxContainer::iterator L0_boxes_itr(L0_boxes);
         for (int i = 0; i < my_boxes_start; ++i) {
            ++L0_boxes_itr;
         }
         for (int i = my_boxes_start; i < my_boxes_stop; ++i, L0_boxes_itr++) {
            L0.addBox(*L0_boxes_itr, hier::BlockId::zero());
         }

         /*
          * Load balance the L0 BoxLevel, using the domain as its L0.
          *
          * This is not a part of the performance test because does not
          * reflect the load balancer use in real apps.  We just neeed a
          * distributed L0 for the real load balancing performance test.
          */
         hier::Connector L0_to_domain(
            L0,
            domain_box_level,
            hier::IntVector(dim, 2));
         hier::Connector domain_to_L0(
            domain_box_level,
            L0,
            hier::IntVector(dim, 2));
         oca.findOverlaps(L0_to_domain);
         oca.findOverlaps(domain_to_L0);

         boost::shared_ptr<mesh::LoadBalanceStrategy> lb0 =
            createLoadBalancer( base_db, load_balancer_type, 0, dim );

         tbox::plog << "\n\tL0 prebalance loads:\n";
         mesh::BalanceUtilities::gatherAndReportLoadBalance(
            (double)L0.getLocalNumberOfCells(),
            L0.getMPI());

         tbox::pout << "\tPartitioning..." << std::endl;

         outputPrebalance( L0, domain_box_level, ghost_cell_width, "L0: " );

         if ( load_balance[0] ) {
            tbox::SAMRAI_MPI::getSAMRAIWorld().Barrier();
            lb0->loadBalanceBoxLevel(
               L0,
               L0_to_domain,
               domain_to_L0,
               hierarchy,
               0,
               hier::Connector(),
               hier::Connector(),
               hierarchy->getSmallestPatchSize(0),
               hierarchy->getLargestPatchSize(0),
               domain_box_level,
               bad_interval,
               cut_factor);
         }

         sortNodes(L0,
            domain_to_L0,
            L0_to_domain,
            false,
            true);

         tbox::plog << "\n\tL0 postbalance loads:\n";
         mesh::BalanceUtilities::gatherAndReportLoadBalance(
            (double)L0.getLocalNumberOfCells(),
            L0.getMPI());

         outputPostbalance( L0, domain_box_level, ghost_cell_width, "L0: " );

         L0.cacheGlobalReducedData();

         hierarchy->makeNewPatchLevel(0, L0);
      }

      const hier::BoxLevel &L0 = *hierarchy->getPatchLevel(0)->getBoxLevel();



      hier::Connector L1_to_L0;
      hier::Connector L0_to_L1;
      hier::Connector L1_to_L1;



      if ( max_levels > 1 ) {
         /*
          * Step 2: Build L1.
          */
         tbox::pout << "\n==================== Generating L1 ====================" << std::endl;

         hier::BoxLevel L1(dim);

         const int coarser_ln = 0;
         const int finer_ln = coarser_ln + 1;

         // Get the prebalanced L1:
         const hier::IntVector required_connector_width =
            hierarchy->getRequiredConnectorWidth(coarser_ln, finer_ln);
         const hier::IntVector min_size = hier::IntVector::ceilingDivide(
            hierarchy->getSmallestPatchSize(finer_ln), hierarchy->getRatioToCoarserLevel(finer_ln) );


         /*
          * Tag cells.
          */
         tbox::pout << "\tTagging..." << std::endl;
         bool exact_tagging = false;
         hierarchy->getPatchLevel(coarser_ln)->allocatePatchData(tag_data_id);
         mesh_gen->setTags( exact_tagging, hierarchy, coarser_ln, tag_data_id );


         /*
          * Cluster.
          */
         tbox::pout << "\tClustering..." << std::endl;
         abr.setMPI(L0.getMPI());
         tbox::SAMRAI_MPI::getSAMRAIWorld().Barrier();
         abr.findBoxesContainingTags(
            L1,
            L0_to_L1,
            L1_to_L0,
            hierarchy->getPatchLevel(coarser_ln),
            tag_data_id,
            1 /* tag_val */,
            L0.getGlobalBoundingBox(0),
            min_size,
            exact_tagging ? 1.0 : efficiency_tol,
            exact_tagging ? 1.0 : combine_tol,
            required_connector_width,
            hier::BlockId::zero(),
            hier::LocalId(0));

         outputPostcluster( L1, L0, required_connector_width, "L1: " );

         /*
          * Enforce nesting.
          */
         if ( enforce_nesting[1] ) {
            enforceNesting(
               L1,
               L0_to_L1,
               L1_to_L0,
               hierarchy,
               coarser_ln);
         }

         if ( L1.getGlobalNumberOfBoxes() == 0 ) {
            TBOX_ERROR("Level " << finer_ln << " box generator resulted in no boxes.");
         }

         boost::shared_ptr<mesh::LoadBalanceStrategy> lb1
            = createLoadBalancer( base_db, load_balancer_type, 1 , dim);

         tbox::pout << "\tPartitioning..." << std::endl;

         outputPrebalance( L1, L0, required_connector_width, "L1: " );

         tbox::plog << "\n\tL1 prebalance loads:\n";
         mesh::BalanceUtilities::gatherAndReportLoadBalance(
            (double)L1.getLocalNumberOfCells(),
            L1.getMPI());

         if ( load_balance[1] ) {
            tbox::SAMRAI_MPI::getSAMRAIWorld().Barrier();
            lb1->loadBalanceBoxLevel(
               L1,
               L1_to_L0,
               L0_to_L1,
               hierarchy,
               1,
               hier::Connector(),
               hier::Connector(),
               hier::IntVector::ceilingDivide(hierarchy->getSmallestPatchSize(1), hierarchy->getRatioToCoarserLevel(1)),
               hier::IntVector::ceilingDivide(hierarchy->getLargestPatchSize(1), hierarchy->getRatioToCoarserLevel(1)),
               domain_box_level,
               bad_interval,
               cut_factor);
         }

         sortNodes(L1,
                   L0_to_L1,
                   L1_to_L0,
                   false,
                   true);

         outputPostbalance( L1, L0, required_connector_width, "L1: " );

         tbox::plog << "\n\tL1 postbalance loads:\n";
         mesh::BalanceUtilities::gatherAndReportLoadBalance(
            (double)L1.getLocalNumberOfCells(),
            L1.getMPI());

         if ( hierarchy->getRatioToCoarserLevel(1) != zero_vec ) {
            refineHead(
               L1,
               L0_to_L1,
               L1_to_L0,
               hierarchy->getRatioToCoarserLevel(1) );
         }

         // Get the L1_to_L1 for edge statistics.
         oca.bridge(
            L1_to_L1,
            L1_to_L0,
            L0_to_L1,
            L1_to_L0,
            L0_to_L1);

         hierarchy->makeNewPatchLevel(1, L1);
      }

      const hier::BoxLevel &L1 = *hierarchy->getPatchLevel(1)->getBoxLevel();

      hier::Connector L2_to_L1;
      hier::Connector L1_to_L2;
      hier::Connector L2_to_L2;

      if ( max_levels > 2 ) {
         /*
          * Step 3: Build L2.
          */
         tbox::pout << "\n==================== Generating L2 ====================" << std::endl;

         hier::BoxLevel L2(dim);

         const int coarser_ln = 1;
         const int finer_ln = coarser_ln + 1;

         // Get the prebalanced L2:
         const hier::IntVector required_connector_width =
            hierarchy->getRequiredConnectorWidth(coarser_ln, finer_ln);
         const hier::IntVector min_size = hier::IntVector::ceilingDivide(
            hierarchy->getSmallestPatchSize(finer_ln), hierarchy->getRatioToCoarserLevel(finer_ln) );


         /*
          * Tag cells.
          */
         tbox::pout << "\tTagging..." << std::endl;
         bool exact_tagging = false;
         hierarchy->getPatchLevel(coarser_ln)->allocatePatchData(tag_data_id);
         mesh_gen->setTags( exact_tagging, hierarchy, coarser_ln, tag_data_id );


         /*
          * Cluster.
          */
         tbox::pout << "\tClustering..." << std::endl;
         abr.setMPI(L0.getMPI());
         tbox::SAMRAI_MPI::getSAMRAIWorld().Barrier();
         abr.findBoxesContainingTags(
            L2,
            L1_to_L2,
            L2_to_L1,
            hierarchy->getPatchLevel(coarser_ln),
            tag_data_id,
            1 /* tag_val */,
            L1.getGlobalBoundingBox(0),
            min_size,
            exact_tagging ? 1.0 : efficiency_tol,
            exact_tagging ? 1.0 : combine_tol,
            required_connector_width,
            hier::BlockId::zero(),
            hier::LocalId(0));

         outputPostcluster( L2, L1, required_connector_width, "L2: " );

         /*
          * Enforce nesting.
          */
         if ( enforce_nesting[2] ) {
            enforceNesting(
               L2,
               L1_to_L2,
               L2_to_L1,
               hierarchy,
               coarser_ln);
         }

         if ( L2.getGlobalNumberOfBoxes() == 0 ) {
            TBOX_ERROR("Level " << finer_ln << " box generator resulted in no boxes.");
         }


         boost::shared_ptr<mesh::LoadBalanceStrategy> lb2
            = createLoadBalancer( base_db, load_balancer_type, 2 , dim);

         tbox::pout << "\tPartitioning..." << std::endl;

         outputPrebalance( L2, L1, required_connector_width, "L2: " );

         tbox::plog << "\n\tL2 prebalance loads:\n";
         mesh::BalanceUtilities::gatherAndReportLoadBalance(
            (double)L2.getLocalNumberOfCells(),
            L2.getMPI());

         if ( load_balance[2] ) {
            tbox::SAMRAI_MPI::getSAMRAIWorld().Barrier();
            lb2->loadBalanceBoxLevel(
               L2,
               L2_to_L1,
               L1_to_L2,
               hierarchy,
               1,
               hier::Connector(),
               hier::Connector(),
               hier::IntVector::ceilingDivide(hierarchy->getSmallestPatchSize(2), hierarchy->getRatioToCoarserLevel(2)),
               hier::IntVector::ceilingDivide(hierarchy->getLargestPatchSize(2), hierarchy->getRatioToCoarserLevel(2)),
               domain_box_level,
               bad_interval,
               cut_factor);
         }

         sortNodes(L2,
                   L1_to_L2,
                   L2_to_L1,
                   false,
                   true);

         outputPostbalance( L2, L1, required_connector_width, "L2: " );

         tbox::plog << "\n\tL2 postalance loads:\n";
         mesh::BalanceUtilities::gatherAndReportLoadBalance(
            (double)L2.getLocalNumberOfCells(),
            L2.getMPI());

         if ( hierarchy->getRatioToCoarserLevel(2) != zero_vec ) {
            refineHead(
               L2,
               L1_to_L2,
               L2_to_L1,
               hierarchy->getRatioToCoarserLevel(2) );
         }

         // Get the L2_to_L2 for edge statistics.
         oca.bridge(
            L2_to_L2,
            L2_to_L1,
            L1_to_L2,
            L2_to_L1,
            L1_to_L2);

         hierarchy->makeNewPatchLevel(2, L2);
      }

      // const hier::BoxLevel &L2 = *hierarchy->getPatchLevel(2)->getBoxLevel();


      tbox::plog << "\n==================== Final hierarchy ====================" << std::endl;
      for ( int ln=0; ln<hierarchy->getNumberOfLevels(); ++ln ) {
         tbox::plog << '\n'
                    << "\tL" << ln << " summary:\n"
                    << hierarchy->getPatchLevel(ln)->getBoxLevel()->format("\t\t", 0)
                    << "\tL" << ln << " statistics:\n"
                    << hierarchy->getPatchLevel(ln)->getBoxLevel()->formatStatistics("\t\t");
      }
      tbox::plog << "\n\n";


      bool write_visit =
         main_db->getBoolWithDefault("write_visit", false);
      if ( write_visit ) {
#ifdef HAVE_HDF5

         if ((dim == tbox::Dimension(2)) || (dim == tbox::Dimension(3))) {
            /*
             * Create the VisIt data writer.
             * Write the plot file.
             */
            DerivedVisOwnerData owner_writer;
            const std::string visit_filename = base_name + ".visit";
            appu::VisItDataWriter visit_data_writer(dim,
                                                    "VisIt Writer",
                                                    visit_filename);
            visit_data_writer.registerDerivedPlotQuantity("Owner",
                                                          "SCALAR",
                                                          &owner_writer);
            visit_data_writer.writePlotData(hierarchy, 0);
         }
#else
         TBOX_WARNING("main: You set write_visit to TRUE,\n"
                      << "but VisIt dumps are not supported due to\n"
                      << "not having configured with HDF5.\n");
#endif
      }

   }

   /*
    * Output timer results.
    */
   tbox::TimerManager::getManager()->print(tbox::plog);


   /*
    * Print input database again to fully show usage.
    */
   plog << "Input database after running..." << std::endl;
   tbox::InputManager::getManager()->getInputDatabase()->printClassData(plog);

   tbox::pout << "\nPASSED:  MeshGeneration" << std::endl;

   /*
    * Exit properly by shutting down services in correct order.
    */
   tbox::plog << "\nShutting down..." << std::endl;

   /*
    * Shut down.
    */
   SAMRAIManager::shutdown();
   SAMRAIManager::finalize();

   if (fail_count == 0) {
      SAMRAI_MPI::finalize();
   } else {
      std::cout << "Process " << std::setw(5) << rank << " aborting."
                << std::endl;
      tbox::Utilities::abort("Aborting due to nonzero fail count",
         __FILE__, __LINE__);
   }

   return fail_count;
}



/*
****************************************************************************
* Output post-cluster metadata.
****************************************************************************
*/
void outputPostcluster(
   const hier::BoxLevel &cluster,
   const hier::BoxLevel &ref,
   const hier::IntVector &ref_to_cluster_width,
   const std::string &border )
{
   const hier::IntVector cluster_to_ref_width =
      hier::Connector::convertHeadWidthToBase(
         cluster.getRefinementRatio(),
         ref.getRefinementRatio(),
         ref_to_cluster_width);

   const hier::Connector &cluster_to_ref =
      cluster.getPersistentOverlapConnectors().findOrCreateConnector(
         ref, ref_to_cluster_width, true );

   cluster.cacheGlobalReducedData();
   cluster_to_ref.cacheGlobalReducedData();

   tbox::plog << "\n\n"
              << border << "Cluster summary:\n"
              << cluster.format( border + "\t", 0 )
              << border << "Cluster stats:\n"
              << cluster.formatStatistics( border + "\t" );

   tbox::plog << '\n'
              << border << "cluster--->ref summary:\n"
              << cluster_to_ref.format( border + "\t", 0 )
              << border << "cluster--->ref stats:\n"
              << cluster_to_ref.formatStatistics( border + "\t" );

   return;
}



/*
****************************************************************************
* Output pre-balance metadata.
* - pre-balance level
* - pre--->pre for proximity contrast to post--->post
* - pre--->ref for proximity contrast to post--->pre
* - ref--->pre for proximity contrast to ref--->post
****************************************************************************
*/
void outputPrebalance(
   const hier::BoxLevel &pre,
   const hier::BoxLevel &ref,
   const hier::IntVector &pre_width,
   const std::string &border )
{
   const hier::IntVector ref_width =
      hier::Connector::convertHeadWidthToBase(
         ref.getRefinementRatio(),
         pre.getRefinementRatio(),
         pre_width);

   const hier::Connector &pre_to_pre =
      pre.getPersistentOverlapConnectors().findOrCreateConnector(
         pre, pre_width, true );

   tbox::plog << "\n\n"
              << border << "Prebalance summary:\n"
              << pre.format( border + "\t", 0 )
              << border << "Prebalance stats:\n"
              << pre.formatStatistics( border + "\t" );

   tbox::plog << '\n'
              << border << "pre--->pre summary:\n"
              << pre_to_pre.format( border + "\t", 0 )
              << border << "pre--->pre stats:\n"
              << pre_to_pre.formatStatistics( border + "\t" );

   return;
}



/*
****************************************************************************
* Output post-balance metadata:
* - post-balance level
* - post--->post for proximity evaluation
* - post--->ref for proximity contrast to pre--->ref
* - ref--->post for proximity contrast to ref--->pre
****************************************************************************
*/
void outputPostbalance(
   const hier::BoxLevel &post,
   const hier::BoxLevel &ref,
   const hier::IntVector &post_width,
   const std::string &border )
{
   const hier::IntVector ref_width =
      hier::Connector::convertHeadWidthToBase(
         ref.getRefinementRatio(),
         post.getRefinementRatio(),
         post_width);

   const hier::Connector &post_to_post =
      post.getPersistentOverlapConnectors().findOrCreateConnector(
         post, post_width, true );

   const hier::Connector &post_to_ref =
      post.getPersistentOverlapConnectors().findOrCreateConnector(
         ref, post_width, true );

   const hier::Connector &ref_to_post =
      ref.getPersistentOverlapConnectors().findOrCreateConnector(
         post, ref_width, true );

   tbox::plog << "\n\n"
              << border << "Postbalance summary:\n"
              << post.format( border + "\t", 0 )
              << border << "Postbalance stats:\n"
              << post.formatStatistics( border + "\t" );

   tbox::plog << '\n'
              << border << "post--->post summary:\n"
              << post_to_post.format( border + "\t", 0 )
              << border << "post--->post stats:\n"
              << post_to_post.formatStatistics( border + "\t" );

   tbox::plog << '\n'
              << border << "post--->ref summary:\n"
              << post_to_ref.format( border + "\t", 0 )
              << border << "post--->ref stats:\n"
              << post_to_ref.formatStatistics( border + "\t" );

   tbox::plog << '\n'
              << border << "ref--->post summary:\n"
              << ref_to_post.format( border + "\t", 0 )
              << border << "ref--->post stats:\n"
              << ref_to_post.formatStatistics( border + "\t" );

   return;
}



/*
 ***********************************************************************
 ***********************************************************************
 */
void sortNodes(
   hier::BoxLevel& new_box_level,
   hier::Connector& tag_to_new,
   hier::Connector& new_to_tag,
   bool sort_by_corners,
   bool sequentialize_global_indices)
{
   const hier::MappingConnectorAlgorithm mca;

   hier::Connector sorting_map;
   hier::BoxLevel seq_box_level(new_box_level.getDim());
   hier::BoxLevelConnectorUtils dlbg_edge_utils;
   dlbg_edge_utils.makeSortingMap(
      seq_box_level,
      sorting_map,
      new_box_level,
      sort_by_corners,
      sequentialize_global_indices);

   mca.modify(tag_to_new,
      new_to_tag,
      sorting_map,
      &new_box_level);

   return;
}




/*
 ***********************************************************************
 ***********************************************************************
 */
void refineHead(
   hier::BoxLevel& head,
   hier::Connector& ref_to_head,
   hier::Connector& head_to_ref,
   const hier::IntVector &refinement_ratio )
{
   head.refineBoxes(
      head,
      refinement_ratio,
      head.getRefinementRatio()*refinement_ratio);
   head.finalize();

   const hier::IntVector& head_to_ref_width =
      refinement_ratio * head_to_ref.getConnectorWidth();
   head_to_ref.setBase(head);
   head_to_ref.setWidth(head_to_ref_width, true);

   ref_to_head.setHead(head, true);
   ref_to_head.refineLocalNeighbors(refinement_ratio);

   return;
}



boost::shared_ptr<mesh::LoadBalanceStrategy>
createLoadBalancer(
   boost::shared_ptr<tbox::Database> &input_db,
   const std::string &lb_type,
   int ln,
   const tbox::Dimension &dim )
{

   if (lb_type == "TreeLoadBalancer") {

      boost::shared_ptr<mesh::TreeLoadBalancer>
         tree_lb(new mesh::TreeLoadBalancer(
            dim,
            std::string("mesh::TreeLoadBalancer") + tbox::Utilities::intToString(ln),
            input_db->getDatabaseWithDefault("TreeLoadBalancer",
                                             boost::shared_ptr<tbox::Database>())));
      tree_lb->setSAMRAI_MPI(tbox::SAMRAI_MPI::getSAMRAIWorld());
      return tree_lb;

   }else if (lb_type == "TreeLoadBalancerOld") {

      boost::shared_ptr<mesh::TreeLoadBalancerOld>
         tree_lb(new mesh::TreeLoadBalancerOld(
            dim,
            std::string("mesh::TreeLoadBalancerOld") + tbox::Utilities::intToString(ln),
            input_db->getDatabaseWithDefault("TreeLoadBalancerOld",
                                             boost::shared_ptr<tbox::Database>())));
      tree_lb->setSAMRAI_MPI(tbox::SAMRAI_MPI::getSAMRAIWorld());
      return tree_lb;

   } else if (lb_type == "ChopAndPackLoadBalancer") {

      boost::shared_ptr<mesh::ChopAndPackLoadBalancer>
         cap_lb(new mesh::ChopAndPackLoadBalancer(
            dim,
            std::string("mesh::ChopAndPackLoadBalancer") + tbox::Utilities::intToString(ln),
            input_db->getDatabaseWithDefault("ChopAndPackLoadBalancer",
                                             boost::shared_ptr<tbox::Database>())));
      return cap_lb;

   }
   else {
      TBOX_ERROR(
         "Missing or bad load_balancer specification in Main database.\n"
         << "Specify load_balancer_type = STRING, where STRING can be\n"
         << "\"ChopAndPackLoadBalancer\" or \"TreeLoadBalancer\".");
   }

   return boost::shared_ptr<mesh::LoadBalanceStrategy>();
}




/*
************************************************************************
************************************************************************
*/
void enforceNesting(
   hier::BoxLevel& L1,
   hier::Connector& L0_to_L1,
   hier::Connector& L1_to_L0,
   const boost::shared_ptr<hier::PatchHierarchy>& hierarchy,
   int coarser_ln)
{
   tbox::pout << "\tEnforcing nesting..." << std::endl;

   const tbox::Dimension dim(hierarchy->getDim());

   const int cell_count = L1.getGlobalNumberOfCells();

   /*
    * Make L1 nest inside L0 by nesting_width.
    */
   const hier::IntVector nesting_width(dim, hierarchy->getProperNestingBuffer(coarser_ln));
   hier::BoxLevel L1nested(dim);
   hier::Connector L1_to_L1nested;
   hier::BoxLevelConnectorUtils blcu;
   blcu.computeInternalParts( L1nested,
                              L1_to_L1nested,
                              L1_to_L0,
                              -nesting_width,
                              hierarchy->getGridGeometry()->getDomainSearchTree() );
   hier::MappingConnectorAlgorithm mca;
   mca.modify( L0_to_L1,
               L1_to_L0,
               L1_to_L1nested,
               &L1,
               &L1nested );

   /*
    * Remove overflow nesting.
    */
   blcu.computeInternalParts( L1nested,
                              L1_to_L1nested,
                              L1_to_L0,
                              hier::IntVector::getZero(dim),
                              hierarchy->getGridGeometry()->getDomainSearchTree() );
   mca.modify( L0_to_L1,
               L1_to_L0,
               L1_to_L1nested,
               &L1,
               &L1nested );

   if ( cell_count != L1.getGlobalNumberOfCells() ) {
      tbox::plog << "\t\tWarning: enforceNesting changed number of cells from " << cell_count
                 << " to " << L1.getGlobalNumberOfCells() << '\n';
   }
   else {
      tbox::plog << "\t\tenforceNesting left number of cells at " << cell_count << '\n';
   }

   return;
}
