#!/bin/csh
module load gcc/11.1.0
module load netcdf-c
module load netcdf-cxx4
module load hdf5
module load boost
module load cuda/11
module load python
module load cmake

rm -rf CMakeCache.txt
rm -rf CMakeFiles/
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/3d/*.f

cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=gfortran \
      -DMPIEXEC_EXECUTABLE="/sw/summit/xalt/1.2.1/bin/jsrun" \
      -DMPIEXEC_NUMPROCS_FLAG="-n" \
      -DMPIEXEC_PREFLAGS="-a1;-c7;-bpacked:2;-g1" \
      -DSAMRAI_DIR=$HOME/SAMRAI/SAMRAI-v4.1.0/install_gcc \
      -DHYPRE_DIR=$HOME/hypre/summit_gcc_cpu \
      -DSUNDIALS_DIR=$HOME/sundials/sundials-5.7.0/install_gcc \
      -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
      -DCMAKE_PREFIX_PATH=${HOME}/bin:$OLCF_NETCDF_CXX4_ROOT \
      -DNDIM="3" \
      -DTHERMO4PFM_DIR=$HOME/Thermo4PFM \
      -DGPU_OFFLOAD=ON \
      -DCMAKE_CXX_FLAGS="-fopenmp -foffload=-lm -foffload=nvptx-none -foffload="-O3" -fno-stack-protector" \
      -DCMAKE_EXE_LINKER_FLAGS="-lm -fopenmp" \
      ..

