#!/bin/sh
source ../scripts/modules.condo

rm -rf CMakeCache.txt
rm -rf CMakeFiles
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/2d/*.f

export PKG_CONFIG_PATH=/home/q8j/custom_pkgconfig

cmake -DCMAKE_CXX_COMPILER=mpiCC \
      -DCMAKE_CXX_FLAGS="-Wall" \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=mpif77 \
      -DSAMRAI_DIR=$HOME/SAMRAI/SAMRAI-v4.1.0 \
      -DHYPRE_DIR=$HOME/hypre/hypre2.32.0 \
      -DSUNDIALS_DIR=$HOME/sundials/sundials-5.4.0 \
      -DCMAKE_BUILD_TYPE=Release \
      -DAMPE_WITH_CLANG_FORMAT=ON \
      -DCMAKE_PREFIX_PATH="${HOME}/bin" \
      -DNDIM="2" \
      -DTHERMO4PFM_DIR=$HOME/Thermo4PFM \
      -DCMAKE_PREFIX_PATH=${HOME}/bin \
      -DUSE_PYTHON_ENV=$HOME/my_netcdf_env \
      -DMPIEXEC_EXECUTABLE=/usr/bin/srun \
      -DMPIEXEC_NUMPROC_FLAG="-n" \
      ..

