#!/usr/bin/env bash
module load intel/2022.1.0-magic
module load hdf5-serial
module load boost
module load netcdf-cxx4-serial
module load cmake
module load python/3.9.12

rm -rf CMakeCache.txt
rm -rf CMakeFiles/
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/2d/*.f

cmake -DCMAKE_CXX_COMPILER=mpic++ \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=mpif77 \
      -DSAMRAI_DIR=/usr/gapps/phasefield/samrai/samrai-4.1.0 \
      -DHYPRE_DIR=/usr/gapps/phasefield/hypre/hypre-2.21.0 \
      -DSUNDIALS_DIR=/usr/gapps/phasefield/sundials/sundials-5.4.0 \
      -DCMAKE_BUILD_TYPE=Release \
      -DNDIM="2" \
      -DTHERMO4PFM_DIR=/usr/gapps/phasefield/Thermo4PFM \
      ..

