#!/bin/sh
source ../scripts/modules.condo

rm -rf CMakeCache.txt
rm -rf CMakeFiles/
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/2d/*.f

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=mpiCC -DCMAKE_C_COMPILER=mpicc \
        -DCMAKE_Fortran_COMPILER=mpif77 \
        -DSAMRAI_DIR=$HOME/SAMRAI/cvode-projection \
        -DHYPRE_DIR=$HOME/hypre/hypre-2.11.1/src/hypre \
        -DSUNDIALS_DIR=$HOME/sundials/cvode-projection/install \
        -DNetCDF_CXX_ROOT=$NETCDF_DIR \
        -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
        -DAMPE_WITH_CLANG_FORMAT=ON \
        -DCMAKE_PREFIX_PATH=${HOME}/bin \
        -DNDIM="2" \
        ..

