#!/bin/csh
module load PrgEnv-cray
module load boost
module load cmake
module load cray-python
module load rocm
module load cray-hdf5-parallel/1.12.0.7
module load cray-netcdf-hdf5parallel/4.7.4.7
module load hypre/2.22.0

rm -rf CMakeCache.txt
rm -rf CMakeFiles/
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/3d/*.f

cmake -DCMAKE_CXX_COMPILER=CC -DCMAKE_C_COMPILER=cc \
        -DCMAKE_Fortran_COMPILER=ftn \
        -DSAMRAI_DIR=/ccs/proj/mat190/samrai/SAMRAI-v4.1.0/install_spock \
        -DHYPRE_DIR=$OLCF_HYPRE_ROOT \
        -DSUNDIALS_DIR=/ccs/proj/mat190/sundials/sundials-5.7.0/install_spock \
        -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_PREFIX_PATH=${HOME}/bin \
        -DTHERMO4PFM_DIR=/ccs/proj/mat190/Thermo4PFM/install_crusher_cpu \
        -DNDIM="3" \
        ..

make -j6
