#!/bin/tcsh
#module purge
#module load PrgEnv-gnu
module swap PrgEnv-pgi PrgEnv-gnu
module load craype-network-gemini
module load cray-mpich
module load cray-netcdf
module load cray-hdf5
module load boost/1.62.0

./configure --build=x86_64 --host=x86_64-linux --disable-debug --enable-opt \
            --with-CXX=CC \
            --with-CC=cc \
            --with-F77=ftn \
            --with-MPICC=cc \
            --with-mpi-lib-dirs=$MPICH_DIR \
            --with-boost=$OLCF_BOOST_ROOT \
            --with-hdf5=$HDF5_DIR \
            --with-netcdf=$NETCDF_DIR \
            --with-hypre=$HOME/hypre/hypre-2.11.1/src/hypre_gnu \
            --prefix=$PWD/build
