#!/bin/sh
./configure --enable-debug \
            --with-CXX=/usr/local/bin/mpig++ \
            --with-CC=/usr/local/bin/mpigcc \
            --with-F77=/usr/local/bin/mpigfortran \
            --with-boost=/usr/local/tools/boost-nompi \
            --with-hdf5=/usr/local/tools/hdf5-gnu-parallel-1.8.5 \
            --with-netcdf=/usr/gapps/phasefield/lib/netcdf-cxx-gnu \
            --with-hypre=/usr/gapps/phasefield/hypre/2.11.1-gnu \
            --prefix=$PWD/build
