#!/bin/sh
i./configure --disable-debug --enable-opt \
            --with-CXX=/usr/local/bin/mpiicpc \
            --with-CC=/usr/local/bin/mpiicc \
            --with-F77=/usr/local/bin/ifort \
            --with-boost=/usr/local/tools/boost-nompi \
            --with-hdf5=/usr/local/tools/hdf5-intel-parallel-1.8.8 \
            --with-netcdf=/usr/gapps/phasefield/lib/netcdf-cxx \
            --with-hypre=/usr/gapps/phasefield/hypre/2.11.1 \
            --prefix=$PWD/build
