#!/bin/sh
module purge
module load PE-gnu
module load hdf5
module load netcdf
module load hypre
module load boost

./configure --disable-debug --enable-opt \
            --with-CXX=mpiCC \
            --with-CC=mpicc \
            --with-F77=mpif77 \
            --with-boost=$BOOST_DIR \
            --with-hdf5=$HDF5_DIR \
            --with-hypre=$HYPRE_DIR \
            --with-netcdf=$NETCDF_DIR \
            --prefix=$PWD/build
