#!/bin/tcsh
#Assumes the following modules have been loaded
#module load intel
#module load cray-netcdf
#module load cray-hdf5
#module load boost

./configure --disable-debug --enable-opt \
            --with-CXX=CC \
            --with-CC=cc \
            --with-F77=ftn \
            --with-MPICC=cc \
            --with-mpi-lib-dirs=$MPICH_DIR \
            --with-boost=$BOOST_DIR \
            --with-hdf5=$HDF5_DIR \
            --with-netcdf=$NETCDF_DIR \
            --with-hypre=$HOME/hypre/cori_intel \
            --prefix=$PWD/build
