#!/bin/sh
#Assumes the following modules have been loaded:
#module load intel
#module load hdf5-serial
#module load boost
#module load netcdf

./configure --enable-debug \
            --with-CXX=mpic++ \
            --with-CC=mpicc \
            --with-F77=mpif77 \
            --with-boost=$BOOST_ROOT \
            --with-hdf5=$HDF5 \
            --with-netcdf=/usr/gapps/phasefield/lib/netcdf-cxx-intel \
            --with-hypre=/usr/gapps/phasefield/hypre/2.15.0 \
            --prefix=$PWD/build
