#!/bin/csh
source ../scripts/modules.spock

rm -rf CMakeCache.txt
rm -rf CMakeFiles/
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/3d/*.f

cmake -DCMAKE_CXX_COMPILER=CC -DCMAKE_C_COMPILER=cc \
        -DCMAKE_Fortran_COMPILER=ftn \
        -DSAMRAI_DIR=$HOME/SAMRAI/SAMRAI-v4.1.0/install_spock \
        -DHYPRE_DIR=$HOME/GIT/hypre-space/hypre/install_spock_cpu \
        -DSUNDIALS_DIR=$HOME/sundials/sundials-5.7.0/install_spock \
        -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_PREFIX_PATH=${HOME}/bin \
        -DNDIM="3" \
        ..

