#!/bin/csh
source ../scripts/modules.summit

rm -rf CMakeCache.txt
rm -rf CMakeFiles/
rm cmake_install.cmake
rm Makefile
rm -f ../source/fortran/3d/*.f

cmake -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc \
        -DCMAKE_Fortran_COMPILER=xlf \
        -DMPIEXEC_EXECUTABLE="/sw/summit/xalt/1.2.1/bin/jsrun" \
        -DMPIEXEC_NUMPROCS_FLAG="-n" \
        -DMPIEXEC_PREFLAGS="-a1;-c7;-bpacked:2;-g1" \
        -DSAMRAI_DIR=$HOME/SAMRAI/SAMRAI-v4.1.0/install_xl \
        -DHYPRE_DIR=$HOME/GIT/hypre-space/hypre/summit_xl_cpu \
        -DSUNDIALS_DIR=$HOME/sundials/sundials-5.7.0/install_xl \
        -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_PREFIX_PATH=${HOME}/bin:$OLCF_NETCDF_CXX4_ROOT \
        -DNDIM="3" \
        ..

